"""Charter Synthesizer orchestrator — public entrypoints.

This module owns the top-level entry points for the synthesizer pipeline:
- synthesize(request) → SynthesisResult
- resynthesize(request, topic) → SynthesisResult

Both functions use lazy imports to delegate to their respective pipeline
modules. This keeps WP01's tests independent of WP02/WP05 implementations
while preserving a clean ownership boundary: downstream WPs deliver their
pipeline modules; they do NOT edit this file.

Adapter injection
-----------------
Both entry points accept an optional `adapter` argument. When not supplied,
the production adapter is selected (WP05 / CLI wiring — outside WP01 scope).
Tests pass a FixtureAdapter instance explicitly.

WP02 pipeline (synthesize_pipeline.py) is owned by WP02.
WP05 pipeline (resynthesize_pipeline.py) is owned by WP05.

See plan.md §KD-1, §KD-6.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from .reconcile import SynthesizeMode

__all__ = [
    "SynthesisResult",
    "SynthesizeMode",
    "resynthesize",
    "synthesize",
]


if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path
    from typing import Any

    from .adapter import AdapterOutput, SynthesisAdapter
    from .reconcile import ReconciliationDelta
    from .request import SynthesisRequest
    from .resynthesize_pipeline import ResynthesisResult
    from .synthesize_pipeline import ProvenanceEntry


# ---------------------------------------------------------------------------
# Result type (owned by WP01; WP02 populates fields)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SynthesisResult:
    """Per-target result assembled by the synthesis pipeline.

    Fields are populated by WP02 (synthesize_pipeline.py). WP01 defines the
    type so downstream WPs share a common output contract.
    """

    target_kind: str
    target_slug: str
    adapter_output: AdapterOutput
    """Raw adapter output; orchestration validates and writes it."""

    inputs_hash: str
    """Full SHA-256 hex digest of the normalized SynthesisRequest."""

    effective_adapter_id: str
    """adapter_id_override if set; else adapter.id."""

    effective_adapter_version: str
    """adapter_version_override if set; else adapter.version."""

    reconciliation: ReconciliationDelta | None = None
    """Preserve/prune/dry-run delta from reconciling this run's overlay +
    manifest against on-disk state (WP01, FR-009). ``synthesize()`` always
    populates this; ``None`` only guards construction sites that predate the
    reconciliation seam (``resynthesize()`` does not reconcile — it runs its
    own bounded merge — and leaves this at the default)."""


def _built_in_drg_from_snapshot(snapshot: object) -> object:
    """Normalize a request DRG snapshot into a validate-able DRGGraph payload."""
    if not isinstance(snapshot, dict):
        return snapshot

    normalized = dict(snapshot)
    normalized.setdefault("nodes", [])
    normalized.setdefault("edges", [])
    normalized["schema_version"] = "1.0"
    normalized.setdefault("generated_at", "1970-01-01T00:00:00+00:00")
    normalized.setdefault("generated_by", "request.drg_snapshot")
    return normalized


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


def _reconstruct_synthesis_result(
    request: SynthesisRequest,
    results: list[tuple[Mapping[str, Any], ProvenanceEntry]],
    reconciliation: ReconciliationDelta,
) -> SynthesisResult:
    """Build the ``SynthesisResult`` for the request's primary target.

    Shared tail for every ``synthesize()`` return path (dry-run included) so
    the reconciliation delta is always attached (T005) and there is exactly
    one place that knows how to fall back to the first result when the
    primary target was not among the synthesized set.
    """
    from kernel.clock import datetime, parse_iso  # noqa: PLC0415

    from .adapter import AdapterOutput as _AdapterOutput  # noqa: PLC0415

    primary_target = request.target
    for body, prov in results:
        if prov.artifact_kind == primary_target.kind and prov.artifact_slug == primary_target.slug:
            return SynthesisResult(
                target_kind=prov.artifact_kind,
                target_slug=prov.artifact_slug,
                adapter_output=_AdapterOutput(
                    body=body,
                    generated_at=parse_iso(prov.generated_at)
                    if not isinstance(prov.generated_at, datetime)
                    else prov.generated_at,
                ),
                inputs_hash=prov.inputs_hash,
                effective_adapter_id=prov.adapter_id,
                effective_adapter_version=prov.adapter_version,
                reconciliation=reconciliation,
            )

    # Fallback to first result if primary target was not among synthesized targets
    first_body, first_prov = results[0]
    return SynthesisResult(
        target_kind=first_prov.artifact_kind,
        target_slug=first_prov.artifact_slug,
        adapter_output=_AdapterOutput(
            body=first_body,
            generated_at=parse_iso(first_prov.generated_at)
            if not isinstance(first_prov.generated_at, datetime)
            else first_prov.generated_at,
        ),
        inputs_hash=first_prov.inputs_hash,
        effective_adapter_id=first_prov.adapter_id,
        effective_adapter_version=first_prov.adapter_version,
        reconciliation=reconciliation,
    )


def synthesize(
    request: SynthesisRequest,
    adapter: SynthesisAdapter | None = None,
    repo_root: Path | None = None,
    *,
    mode: SynthesizeMode = SynthesizeMode.preserve,
) -> SynthesisResult:
    """Run the full synthesis pipeline for a single SynthesisRequest.

    Delegates to synthesize_pipeline.run_all() (WP02), reconciles the fresh
    overlay + manifest against on-disk state (WP01, ``reconcile.py`` —
    preserve-and-succeed: never silently drops backed content, FR-001/FR-009),
    then stages and promotes to disk via write_pipeline.promote() (WP03).

    Parameters
    ----------
    request:
        The fully-populated SynthesisRequest envelope.
    adapter:
        The adapter to use for generation. When None, the production adapter
        is resolved (WP05 / CLI wiring). Tests pass a FixtureAdapter.
    repo_root:
        Repository root for staging/promote. Inferred from CWD when None
        (WP05 / CLI wiring will supply this explicitly).
    mode:
        ``preserve`` (default): reconcile and write, dropping nothing.
        ``dry_run``: compute the ``ReconciliationDelta`` only; write nothing.
        ``prune``: write the merged state minus ``delta.removable``. Keyword-
        only so every existing positional caller (``synthesize(request,
        adapter, repo_root)``) keeps working unchanged.

    Returns
    -------
    SynthesisResult
        Per-target result with validated artifact body + provenance fields,
        carrying the ``ReconciliationDelta`` in ``.reconciliation``. For
        ``preserve``/``prune`` the manifest + artifacts have been written to
        disk before returning; for ``dry_run`` nothing was written.

    Raises
    ------
    NotImplementedError
        Until WP02 delivers synthesize_pipeline.py (pre-WP02 state).
    ImportError
        Propagated if synthesize_pipeline or write_pipeline module is missing.
    doctrine.drg.loader.DRGLoadError
        When an on-disk project overlay exists but cannot be parsed (FR-007
        fail-closed at the library seam — never falls back to a wholesale
        rebuild; see ``reconcile.reconcile_synthesis``).
    """
    from pathlib import Path as _Path  # noqa: PLC0415

    try:
        from doctrine.drg.models import DRGGraph as _DRGGraph  # noqa: PLC0415
        from .interview_mapping import normalize_interview_snapshot as _normalize_interview_snapshot  # noqa: PLC0415
        from .interview_mapping import resolve_sections as _resolve_sections  # noqa: PLC0415
        from .project_drg import apply_post_condition as _apply_post_condition  # noqa: PLC0415
        from .project_drg import emit_project_layer as _emit_project_layer  # noqa: PLC0415
        from .project_drg import persist as _persist_project_graph  # noqa: PLC0415
        from .reconcile import apply_prune as _apply_prune  # noqa: PLC0415
        from .reconcile import reconcile_synthesis as _reconcile_synthesis  # noqa: PLC0415
        from .synthesize_pipeline import _get_synthesizer_version  # noqa: PLC0415
        from .synthesize_pipeline import run_all as _run_all  # noqa: PLC0415
        from .staging import StagingDir as _StagingDir  # noqa: PLC0415
        from .targets import build_targets as _build_targets  # noqa: PLC0415
        from .targets import detect_duplicates as _detect_duplicates  # noqa: PLC0415
        from .targets import order_targets as _order_targets  # noqa: PLC0415
        from .validation_gate import validate as _validate_project_graph  # noqa: PLC0415
        from . import write_pipeline as _write_pipeline  # noqa: PLC0415
    except ImportError as exc:
        raise NotImplementedError(
            "synthesize() is not yet fully implemented — WP02 must deliver "
            "synthesize_pipeline.py and WP03 must deliver write_pipeline.py."
        ) from exc

    # Version resolution is deliberately outside the import-guard above:
    # importlib.metadata.PackageNotFoundError is a subclass of ImportError
    # (PackageNotFoundError -> ModuleNotFoundError -> ImportError), so calling
    # it inside that try/except previously let an unresolvable-metadata
    # failure masquerade as "synthesize_pipeline.py is missing". Delegate to
    # the package's canonical version helper, which never raises.
    _SPEC_KITTY_VERSION = _get_synthesizer_version()

    # --- In-memory pipeline (WP02) ---
    results = _run_all(request, adapter=adapter)

    built_in_drg = _DRGGraph.model_validate(_built_in_drg_from_snapshot(request.drg_snapshot))
    interview_snapshot = _normalize_interview_snapshot(dict(request.interview_snapshot))
    sections = _resolve_sections(interview_snapshot)
    targets = _build_targets(
        interview_snapshot=interview_snapshot,
        mappings=sections,
        drg_snapshot=dict(request.drg_snapshot),
    )
    targets = _order_targets(targets)
    _detect_duplicates(targets)
    if not targets:
        targets = [request.target]

    _repo_root = repo_root if repo_root is not None else _Path.cwd()

    # --- Reconcile the fresh emit against on-disk state (WP01) ---
    # Computed BEFORE staging (mirrors resynthesize_pipeline.run()'s Step
    # 1/6): the merged manifest must be ready to hand to promote() as
    # manifest_override, and dry_run needs the delta without ever creating a
    # staging dir. May raise DRGLoadError — fail-closed, no write (FR-007).
    fresh_overlay = _emit_project_layer(
        targets=targets,
        spec_kitty_version=_SPEC_KITTY_VERSION,
        built_in_drg=built_in_drg,
    )
    outcome = _reconcile_synthesis(
        repo_root=_repo_root,
        fresh_overlay=fresh_overlay,
        new_results=results,
        run_id=request.run_id,
        built_in_drg=built_in_drg,
    )
    if mode is SynthesizeMode.prune:
        outcome = _apply_prune(outcome)

    if mode is SynthesizeMode.dry_run:
        return _reconstruct_synthesis_result(request, results, outcome.delta)

    merged_overlay = outcome.merged_overlay

    def _validation_callback(staged_dir: _StagingDir) -> None:
        # FR-009 amendment #1 (BLOCKER): persist the MERGED overlay
        # unconditionally when it carries content, and drive the post-
        # condition below from the merged graph — not the fresh emit. A
        # zero/subset-emit run over a backed on-disk overlay must not
        # re-unlink the preserved graph.yaml.
        if merged_overlay.nodes:
            _persist_project_graph(merged_overlay, staged_dir.root, staged_dir.guard)
        # WP01<->WP02 integration seam (ownership leeway): the widened
        # validate() signature (WP02) is inert unless THIS call site (WP01's
        # file) threads WP01's classified conflicts through it, so a
        # preserved-content conflict is suppressed end-to-end instead of
        # still hard-failing here. lane-b is where both halves land, so WP02
        # wires this one line rather than leaving NFR-003 unmet in practice.
        _validate_project_graph(staged_dir.root, built_in_drg, conflicts=outcome.delta.conflicts)

    # --- Stage and promote to disk (WP03, T018) ---
    with _StagingDir.create(_repo_root, request.run_id) as staging_dir:
        _write_pipeline.promote(
            request,
            staging_dir,
            results,
            _validation_callback,
            manifest_override=outcome.merged_manifest,
        )

    # --- FR-009 post-condition: graph.yaml XOR built_in_only=True ---
    _apply_post_condition(
        _repo_root,
        has_project_graph=bool(merged_overlay.nodes),
    )

    return _reconstruct_synthesis_result(request, results, outcome.delta)


def resynthesize(
    request: SynthesisRequest,
    topic: str,
    adapter: SynthesisAdapter | None = None,
) -> SynthesisResult | ResynthesisResult:
    """Run bounded resynthesis for a single structured topic selector.

    Delegates to resynthesize_pipeline.run() (implemented in WP05).

    Parameters
    ----------
    request:
        The SynthesisRequest for the targeted artifact.
    topic:
        Structured selector string (kind:slug | DRG URN | interview section).
    adapter:
        Adapter to use. None → production adapter (WP05 CLI wiring).

    Returns
    -------
    SynthesisResult
        Result for the targeted artifact.

    Raises
    ------
    NotImplementedError
        Until WP05 delivers resynthesize_pipeline.py.
    """
    try:
        from .resynthesize_pipeline import run as _run  # noqa: PLC0415
    except ImportError as exc:
        raise NotImplementedError(
            "resynthesize() is not yet implemented — WP05 will deliver "
            "src/charter/synthesizer/resynthesize_pipeline.py."
        ) from exc

    # The pipeline call is deliberately outside the import-guard above: any
    # ImportError raised while *running* the pipeline (e.g. a transitive
    # importlib.metadata.PackageNotFoundError, which subclasses ImportError)
    # must propagate as itself, not be mislabeled as "resynthesize_pipeline.py
    # is missing".
    return _run(request, topic=topic, adapter=adapter)
