"""Pre-commit hook installer for worktrees.

Installs a Python-based pre-commit hook that invokes the commit guard.
The generated hook pins the absolute Python interpreter path at install time
and does not depend on PATH (FR-009, C-003).
"""

from __future__ import annotations

import os
import sys
import tempfile
from contextlib import suppress
from dataclasses import dataclass
from kernel.clock import now_utc_seconds
from pathlib import Path

HOOK_TEMPLATE = """\
#!/bin/sh
# Generated by spec-kitty. Do not edit by hand.
# Installed: {installed_at}
# Interpreter: {interpreter}
set -e
exec "{interpreter}" -m specify_cli.policy.commit_guard_hook "$@"
"""

MODULE = "specify_cli.policy.commit_guard_hook"
SHEBANG = "#!/bin/sh"
HOOK_MODE = 0o700


@dataclass(frozen=True)
class HookInstallRecord:
    """Record of a successful pre-commit hook installation (data-model E-05)."""

    hook_path: Path
    interpreter: Path
    module: str
    shebang: str
    mode: int


def install(repo_root: Path) -> HookInstallRecord:
    """Install pre-commit hook into a repository, pinning the absolute interpreter.

    Captures ``sys.executable`` at install time so the generated hook does not
    rely on ``python``, ``python3``, or ``py`` being on PATH.  The hook is
    written atomically (temp-file + ``os.replace``) with mode ``0o700`` and
    LF line endings.

    Symlinks in ``sys.executable`` are intentionally **not** resolved. Pipx,
    ``venv``, and ``virtualenv`` rely on Python being launched via the venv's
    ``bin/python`` symlink so site initialization sets ``sys.prefix`` to the
    venv and adds the venv's ``site-packages`` to ``sys.path``. Resolving the
    symlink to the underlying interpreter would strip that context and make
    ``specify_cli`` unimportable from the hook (issue #669).

    Args:
        repo_root: Path to the root of the git repository (must contain ``.git``).

    Returns:
        A :class:`HookInstallRecord` describing the installed hook.

    Raises:
        RuntimeError: If ``sys.executable`` does not refer to an existing file.
    """
    interpreter = Path(os.path.abspath(sys.executable))
    if not interpreter.is_file():
        raise RuntimeError(
            f"Cannot install pre-commit hook: sys.executable={sys.executable!r} "
            f"(absolute: {interpreter}) does not exist."
        )

    installed_at = now_utc_seconds()
    rendered = HOOK_TEMPLATE.format(
        installed_at=installed_at,
        interpreter=str(interpreter),
    )

    hooks_dir = repo_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    fd, tmp_path_str = tempfile.mkstemp(prefix="pre-commit.", dir=str(hooks_dir))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(rendered)
        os.chmod(tmp_path_str, HOOK_MODE)
        os.replace(tmp_path_str, str(hooks_dir / "pre-commit"))
    except Exception:
        with suppress(OSError):
            os.unlink(tmp_path_str)
        raise

    return HookInstallRecord(
        hook_path=hooks_dir / "pre-commit",
        interpreter=interpreter,
        module=MODULE,
        shebang=SHEBANG,
        mode=HOOK_MODE,
    )


def install_commit_guard(_worktree_path: Path, repo_root: Path) -> Path | None:
    """Install pre-commit hook into a worktree.

    Resolves the worktree's git hooks directory and installs the hook there.
    For worktrees, the ``.git`` file points to the worktree-specific git dir,
    so we use the repo_root's ``.git`` directory directly (which is the main
    repo hooks dir shared across all worktrees).

    This is the legacy entrypoint retained for callers that pass both
    ``worktree_path`` and ``repo_root``.  New code should call :func:`install`
    directly with the repository root.

    Args:
        worktree_path: Path to the worktree (unused; retained for API compat).
        repo_root: Path to the main repository root.

    Returns:
        Path to the installed hook, or None if installation failed.
    """
    try:
        record = install(repo_root)
        return record.hook_path
    except Exception:
        return None
